{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spqtify.com.embedImageService.fullname" . }}
  labels:
    {{- include "spqtify.com.labels" . | nindent 4 }}
    app.kubernetes.io/component: embed-image-service
spec:
  podSelector:
    matchLabels:
      {{- include "spqtify.com.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: embed-image-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "spqtify.com.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: {{ index .Values "embed-image-service" "service" "port" }}
{{- end }}
