[[bin]]
name = "api"
path = "src/main.rs"

[package]
name = "api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.97"
axum = { version = "0.8.1", features = ["macros", "query"] }
axum-macros = "0.5.0"
cuid = "1.3.3"
futures = "0.3.31"
reqwest = { version = "0.12.14", features = ["json", "stream", "cookies"] }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = { version = "0.7.14", features = ["io"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
dotenvy = "0.15.7"
chrono = { version = "0.4.40", features = ["serde"] }
once_cell = "1.21.1"
thiserror = "2.0.12"
envconfig = "0.11.0"
backblaze-b2-client = "0.1.7"
bytes = "1.10.1"
tokio-stream = "0.1.17"
opentelemetry = "0.29.1"
opentelemetry-otlp = { version = "0.29.0", features = ["grpc-tonic"] }
axum-tracing-opentelemetry = "0.28.0"
init-tracing-opentelemetry = { version = "0.37.0", features = [
    "otlp",
    "tracing_subscriber_ext",
] }
posthog-rs = { version = "0.23.2", default-features = false, features = ["async-client"] }
