name: Build Services
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  build-and-deploy:
    needs: checks
    concurrency:
      group: prod-${{ matrix.app }}-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      # TODO: replace with script that uses turbo+git to 
      # detech what services need building
      fail-fast: false
      matrix:
        include:
          - app: api
            deployment_name: machina/api
            nix_image_attr: apiDockerImage
            version_key: apiVersion
          - app: embed-image-service
            deployment_name: machina/embed-image-service
            nix_image_attr: embedImageServiceDockerImage
            version_key: embedImageServiceVersion
    uses: ./.github/workflows/base-publish.yaml
    with:
      environment: production
      nix_image_attr: ${{ matrix.nix_image_attr }}
      deployment_name: ${{ matrix.deployment_name }}
      argo_deployments_path: "helm/machina/values/production.yaml"
      version_key: ${{ matrix.version_key }}
    secrets: inherit
